<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=0" />
	<title>WebMaker - Informática</title>
	<link rel="shortcut icon" type="image/x-icon" href="css/images/favicon.ico" />
	<link rel="stylesheet" href="../css/style.css" type="text/css" media="all" />
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,900,800,700,600,500,300,200,100' rel='stylesheet' type='text/css'>
	
	<script src="../js/jquery-1.8.0.min.js" type="text/javascript"></script>
	<!--[if lt IE 9]>
		<script src="js/modernizr.custom.js"></script>
	<![endif]-->
	<script src="../js/jquery.carouFredSel-5.5.0-packed.js" type="text/javascript"></script>
	<script src="../js/functions.js" type="text/javascript"></script>
</head>
<body>
<!-- wrapper -->
<div id="wrapper">
	<!-- shell -->
	<div class="shell">
		<!-- container -->
		<div class="container">
			<!-- header -->
			<header id="header">
				<h1 id="logo"><a href="#">WebMaker - Informática</a></h1>
				<!-- search -->
				<div class="search">
					<form action="" method="post">
						<input type="text" class="field" value="palavras-chave aqui ..." title="palavras-chave aqui ..." />
						<input type="submit" class="search-btn" value="" />
						<div class="cl">&nbsp;</div>
					</form>
				</div>
				<!-- end of search -->
				<div class="cl">&nbsp;</div>
			</header>
			<!-- end of header -->
			<!-- navigaation -->
			<nav id="navigation">
				<a href="#" class="nav-btn">Inicio<span></span></a>
				<ul>
					<li class="active"><a href="../home.html">Inicio</a></li>
					<li><a href="sobre.phtml">Sobre</a></li>
					<li><a href="servicos.phtml">Serviços</a></li>
					<li><a href="cursos.phtml">Cursos</a></li>
					<li><a href="acessoonline">Acesso online</a></li>
					<!-- <li><a href="#">jobs</a></li>
					<li><a href="#">blog</a></li> -->
					<li><a href="contato.phtml">Contato</a></li>
				</ul>
				<div class="cl">&nbsp;</div>
			</nav>
			<!-- end of navigation -->
			<!-- slider-holder -->
			<div class="slider-holder">
				
				<!-- slider -->
				<div class="slider">
					<!-- <div class="socials">
						<a href="#" class="facebook-ico">facebook-ico</a>
						<a href="#" class="twitter-ico">twitter-ico</a>
						<a href="#" class="skype-ico">skype-ico</a>
						<a href="#" class="rss-ico">rss-ico</a>
						<div class="cl">&nbsp;</div>
					</div> -->

					<div class="arrs">
						<a href="#" class="prev-arr"></a>
						<a href="#" class="next-arr"></a>
					</div>

					<ul>
						<li id="img1">
							<div class="slide-cnt">
								<h4>Sobre a Empresa</h4>
								<h2>Sobre</h2>
								<p>Fundada em 2013, a WebMaker-Informática inicia suas atividades apenas como prestadora de serviços no setor de Informática e Tecnologia. <a href="php/sobre.phtml">Veja mais</a></p>
							</div>
							<img src="../css/images/empresa.jpg" alt="" width="390" height="277" style="margin-top: 10px;"/>
						</li>

						<li id="img2">
							<div class="slide-cnt">
								<h4>Serviços</h4>
								<h2>Serviços</h2>
								<p>Manutenção de Computadores e Criação de Sistemas e Sites.<a href="php/servicos.phtml">Veja mais</a></p>
							</div>
							
							<img src="../css/images/mac-img.png" alt="" />
						</li>

						<li id="img3">
							<div class="slide-cnt">
								<h4>Cursos online e dvd's</h4>
								<h2>Cursos</h2>
								<p>Faça já o seu curso profissional e seja o melhor da sua área. <a href="php/cursos.phtml">Veja mais</a></p>
							</div>
							<img src="css/images/mac-img.png" alt="" />
						</li>

						 <li id="img4">
							<div class="slide-cnt">
								<h4>Faça já o seu Cadastro</h4>
								<h2>Acesso Online</h2>
								<p>Para ter acesso as Video Aulas Gratis ou Pagas, faça o seu Cadastro. <a href="#">Veja mais</a></p>
							</div>
							<img src="../css/images/acesso-oline.jpg" alt="" width="390" height="277" style="margin-top: 10px;"/>
						</li>

						<li id="img5">
							<div class="slide-cnt">
								<h4>Heading Title Goes</h4>
								<h2>Just Like That</h2>
								<p>Acor porta mi, non venenatis augue imperdiet quis. Nam faucibus, felis ut suscipit vulputate, tortor quam ultricies neque, eget dignissim elit urna a metus. Aliquam sed quam dui, id lacinia nunc. <a href="#">read more</a></p>
							</div>
							<img src="../css/images/mac-img.png" alt="" />
						</li>

					<!--	<li id="img6">
							<div class="slide-cnt">
								<h4>Heading Title Goes</h4>
								<h2>Just Like That</h2>
								<p>Acor porta mi, non venenatis augue imperdiet quis. Nam faucibus, felis ut suscipit vulputate, tortor quam ultricies neque, eget dignissim elit urna a metus. Aliquam sed quam dui, id lacinia nunc. <a href="#">read more</a></p>
							</div>
							<img src="css/images/mac-img.png" alt="" />
						</li>

						<li id="img7">
							<div class="slide-cnt">
								<h4>Heading Title Goes</h4>
								<h2>Just Like That</h2>
								<p>Acor porta mi, non venenatis augue imperdiet quis. Nam faucibus, felis ut suscipit vulputate, tortor quam ultricies neque, eget dignissim elit urna a metus. Aliquam sed quam dui, id lacinia nunc. <a href="#">read more</a></p>
							</div>
							<img src="css/images/mac-img.png" alt="" />
						</li>

						<li id="img8">
							<div class="slide-cnt">
								<h4>Heading Title Goes</h4>
								<h2>Just Like That</h2>
								<p>Acor porta mi, non venenatis augue imperdiet quis. Nam faucibus, felis ut suscipit vulputate, tortor quam ultricies neque, eget dignissim elit urna a metus. Aliquam sed quam dui, id lacinia nunc. <a href="#">read more</a></p>
							</div>
							<img src="css/images/mac-img.png" alt="" />
						</li> -->
					</ul>
				</div>
				<!-- end of slider -->

				<!-- thumbs -->
				<div id="thumbs-wrapper">
					<div id="thumbs">
						<a href="#img1" class="selected"><img src="../css/images/thumb.png"/></a>
						<a href="#img2"><img src="../css/images/thumb2.png" /></a>
						<a href="#img3"><img src="../css/images/thumb3.png" /></a>
						<a href="#img4"><img src="../css/images/thumb4.png" /></a>
						 <a href="#img5"><img src="../css/images/thumb.png" /></a>
						<!--<a href="#img6"><img src="css/images/thumb2.png" /></a>
						<a href="#img7"><img src="css/images/thumb3.png" /></a>
						<a href="#img8"><img src="css/images/thumb4.png" /></a> -->
					</div>
					<a id="prev" href="#"></a>
					<a id="next" href="#"></a>
				</div>
				<!-- end of thumbs -->
			</div>

			<!-- main -->
			<div class="main">

				<div class="featured">
					<h4>Bem Vindo <strong>a WebMakerInfo.</strong> Veja alguns dos nossos cursos  <strong>Gratis!</strong></h4>
					<!-- <a href="#" class="blue-btn">Clique Aqui</a> -->
					<a href="#" class="blue-btn">Em Breve</a>
				</div>
				
				<div class="sobre">
					<h3>ACESSO ONLINE - EM MANUTENÇÃO</h3><br />
					<!-- <p>Fundada em 2013, a WebMaker-Informática inicia suas atividades apenas como prestadora de serviços no setor de Informática e Tecnologia.<br />
						<br />Fundada por Jonatas Luis Prates, atualmente único sócio proprietário da organização, diplomado em técnico em Informática pela ETEC Sylvio de Mattos Carvalho, na cidade de Matão - SP, cursando faculdade IESP de taquaritinga 3°ano de Sistema de Informação. Atuando no ramo de Informática há mais de 4 anos, como técnico em manutenção em microcomputadores, programação e periféricos.
					</p> -->
					
				</div>

				
			</div>
			<!-- end of main -->
			<div class="cl">&nbsp;</div>
			
			<!-- footer -->
			<div id="footer">
				<div class="footer-nav">
					<ul>
						<li><a href="../home.html">Inicio</a></li>
						<li><a href="sobre.phtml">Sobre</a></li>
						<li><a href="servicos.phtml">Serviços</a></li>
						<li><a href="cursos.phtml">Cursos</a></li>
						<li><a href="acessoonline">Acesso online</a></li>
						<!-- <li><a href="#">jobs</a></li>
						<li><a href="#">blog</a></li> -->
						<li><a href="contato.phtml">Contato</a></li>
					</ul>
					<div class="cl">&nbsp;</div>
				</div>
				<p class="copy">2013<span>|</span>WebMakerInfo</a></p>
				<div class="cl">&nbsp;</div>
			</div>
			<!-- end of footer -->
		</div>
		<!-- end of container -->
	</div>
	<!-- end of shell -->
</div>
<!-- end of wrapper -->
</body>
</html>